#!/bin/bash -xeu

set -o pipefail

# Bind the sources with a specific PG version.
# So debian/control is generated.

# PostgreSQL 12.2 (Debian 12.2-4-maruska)
# PG_VERSION=$(pg_config --version |sed -e 's/^PostgreSQL //;s/\.[[:digit:]]\+$//')
PG_VERSION=$(pg_config --version |sed -e 's/^PostgreSQL \([[:digit:]]\+\)\..*$/\1/')
# todo:
if [[ $? != 0 ]]; then
    exit 1
fi
# /;s/\.[[:digit:]]\+$//

packages=(char-in-set coding human max mule natural-sex sadd texify thumbsize)

for pkg in ${packages[@]};
do
    # replace pg-  with  pg-ABI
    sed -e "s/@PKG@/$pkg/g" debian/template.install.in > debian/pg-${PG_VERSION}-${pkg}.install
done

sed -e "s/@PG_VERSION@/$PG_VERSION/" debian/control.in > debian/control
#make -f debian/rules  debian/control
